project_name: production-app

modules:
  project:
    selected: true
    project_name: production-app
    project_id: my-gcp-project-prod-12345
    project_deletion_policy: DELETE
    enabled_apis:
      - compute.googleapis.com
      - sqladmin.googleapis.com
      - run.googleapis.com
      - vpcaccess.googleapis.com
      - secretmanager.googleapis.com
      - cloudresourcemanager.googleapis.com
      - servicenetworking.googleapis.com
      - monitoring.googleapis.com
      - logging.googleapis.com

  network:
    selected: true
    project_id: my-gcp-project-prod-12345
    region: us-central1
    ip_cidr_range: 10.10.0.0/24

  firewall:
    selected: true
    vpc_name: production-app-network
    project_id: my-gcp-project-prod-12345
    allowed_ports_sql: ['5432', '443']
    target_tags_sql: ["sql"]

  sql:
    selected: true
    project_id: my-gcp-project-prod-12345
    project_name: production-app
    region: us-central1
    vpc_name: production-app-network
    db_version: POSTGRES_15
    db_tier: db-custom-2-7680
    db_password_secret: production-app-db-password
    network_id: production-app-network

  secrets:
    selected: true
    project_id: my-gcp-project-prod-12345
    project_name: production-app

  cloudrun:
    selected: true
    project_id: my-gcp-project-prod-12345
    cloudrun_name: production-backend-api
    region: us-central1
    db_name: production-db
    db_port: 5432
    image_name: gcr.io/my-gcp-project-prod-12345/backend-api:v1.2.3
    container_name: backend-api-container
    db_host: 10.10.0.5
    db_user_name: postgres
    db_password_secret: production-app-db-password
    container_port: 8080
    vpc_connector_id: production-app-connector
    sa_email: cloudrun-sa-prod@my-gcp-project-prod-12345.iam.gserviceaccount.com

  vpc_connector:
    selected: true
    project_id: my-gcp-project-prod-12345
    network_id: production-app-network
    region: us-central1
    ip_cidr_range_connector: 10.8.0.0/28

  iam:
    selected: true
    project_id: my-gcp-project-prod-12345
    service_account_id: cloudrun-sa-prod
    display_name: Cloud Run Service Account - Production
    roles:
      - roles/cloudsql.client
      - roles/secretmanager.secretAccessor
      - roles/logging.logWriter
      - roles/monitoring.metricWriter

  load-balancer:
    selected: true
    project_name: production-app
    project_id: my-gcp-project-prod-12345
    region: us-central1
    cloud_run_service_name: production-backend-api

  monitoring:
    selected: true
    project_id: my-gcp-project-prod-12345
    project_name: production-app
    cloud_run_service_name: production-backend-api
    alert_email: devops-team@company.com